name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://jamesshopland.com/

    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update sitemap
        branch: main
        commit_user_name: sitemap-bot # defaults to "GitHub Actions"
        commit_user_email: sitemap-bot@jamesshopland.com # defaults to "actions@github.com"
        push_options: '--force'    
        skip_dirty_check: true    
        skip_fetch: true    
        
        # Optional. Prevents the shell from expanding filenames. 
        # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
        disable_globbing: true


